name: pilates
description: "A pilates management project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter




  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  intl: ^0.20.2  #for date formatting
  image_picker: ^1.0.7
  http: ^1.1.0
  crypto: ^3.0.3
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

 