// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXsiDi7SCjjDD_jgeHXCyiHMafOhBEpnI',
    appId: '1:89272950825:web:27921f57721480f6947c38',
    messagingSenderId: '89272950825',
    projectId: 'pilates-project-70b94',
    authDomain: 'pilates-project-70b94.firebaseapp.com',
    storageBucket: 'pilates-project-70b94.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO36bDAwNolaPCCKR0FGJWd607O-f9S4M',
    appId: '1:89272950825:android:67c8954c448f9a03947c38',
    messagingSenderId: '89272950825',
    projectId: 'pilates-project-70b94',
    storageBucket: 'pilates-project-70b94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZIM3epHBTfDqbszDqRsQFV2NON6LPZkI',
    appId: '1:89272950825:ios:fe9c784a6f40893c947c38',
    messagingSenderId: '89272950825',
    projectId: 'pilates-project-70b94',
    storageBucket: 'pilates-project-70b94.firebasestorage.app',
    iosBundleId: 'com.example.pilates',
  );
}
